### ISSUE TITLE
WithCredentialsJSON() - "private key should be a PEM or plain PKCS1 or PKCS8"

### ISSUE THREAD

**Issue by michealroberts** [googleapis/google-api-go-client#1705]
I'm not sure if this is a bug or a particular problem with env variables usage, but I'd like to understand `WithCredentialsJSON()` that this library provides.

I currently store and transfer all of the sensitive credentials to setup my app in individual environment variables, as I run this particular app locally, within a GitHub action runner, or within a Cloud Run process.

The following code is water tight when running locally, my tests both pass and manual / nominal UATs seem to work fine.

```go
type FirebaseCredentials struct {
	Type                    string `json:"type"`
	ProjectId               string `json:"project_id"`
	PrivateKeyId            string `json:"private_key_id"`
	PrivateKey              string `json:"private_key"`
	ClientEmail             string `json:"client_email"`
	ServiceAccountID        string `json:"service_account_id"`
	ClientId                string `json:"client_id"`
	AuthURI                 string `json:"auth_uri"`
	TokenURI                string `json:"token_uri"`
	AuthProviderX509CertURL string `json:"auth_provider_x509_cert_url"`
	ClientX509CertURL       string `json:"client_x509_cert_url"`
}

func SetupFirebaseApp() (*firebase.App, error) {
	credentials := FirebaseCredentials{
		Type:                    "service_account",
		ProjectId:               os.Getenv("FIREBASE_PROJECT_ID"),
		PrivateKeyId:            os.Getenv("FIREBASE_PRIVATE_KEY_ID"),
		PrivateKey:              strings.Replace(fmt.Sprintf("%v", os.Getenv("FIREBASE_PRIVATE_KEY")), "\\\\\\\n", "\n", -1),
		ClientEmail:             os.Getenv("FIREBASE_CLIENT_EMAIL"),
		ServiceAccountID:        os.Getenv("FIREBASE_SERVICE_ACCOUNT_ID"),
		ClientId:                os.Getenv("FIREBASE_CLIENT_ID"),
		AuthURI:                 "https://accounts.google.com/o/oauth2/auth",
		TokenURI:                "https://oauth2.googleapis.com/token",
		AuthProviderX509CertURL: "https://www.googleapis.com/oauth2/v1/certs",
		ClientX509CertURL:       os.Getenv("FIREBASE_CLIENT_X509_CERT_URL"),
	}

	creds, err := json.Marshal(credentials)

	if err != nil {
		log.Fatalf("error initializing app credentials: %v\n", err)
	}

	app, err := firebase.NewApp(context.Background(), nil, option.WithCredentialsJSON(creds))

	if err != nil {
		log.Fatalf("error initializing app: %v\n", err)
	}

	return app, err
}
```

However, when running within a GitHub action, I see the following error:

```
"https://storage.googleapis.com/upload/storage/v1/b/***/o?alt=json&name=test.txt&prettyPrint=false&projection=full&uploadType=multipart": private key should be a PEM or plain PKCS1 or PKCS8; parse error: asn1: structure error: tags don't match (16 vs {class:0 tag:7 length:45 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} pkcs1PrivateKey @2
```

I'm trying to understand what this means, so I can begin to debug the issue, which is likely due to the way Github secrets are stores.

I have tried to base64 encode the environment variable, and decode as well - but that gives the same error as the above in ALL environments? Surely that shouldn't happen. I have checked the string against what I hvae in my environment .env file, and they are character for character the same. So I am so confused as to why this happens?

#### Steps to reproduce

- Usage of WithCrendetialsJSON() rather than an application credentials file.

- Use and run all environment variables from a Github action as:

```
- name: Go Test
        run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic
        env:
          # Pleiades Firebase Environment Variables
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_SERVICE_ACCOUNT_ID: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ID }}
          FIREBASE_CLIENT_ID: ${{ secrets.FIREBASE_CLIENT_ID }}
          FIREBASE_CLIENT_X509_CERT_URL: ${{ secrets.FIREBASE_CLIENT_X509_CERT_URL }}
```

- Watch the runner fail ...
