### ISSUE TITLE
Consider having generated code use proto field order, not alphabetical

### ISSUE THREAD

**Issue by danielmoy-google** [googleapis/google-api-go-client#302]
This is a feature request, mostly for readability, it doesn't actually hurt anything functionality-wise.

All of the documentation shows things in field order, for example cloud build's docs on building up `cloudbuild.yaml` files:

https://cloud.google.com/cloud-build/docs/build-config#structure_of_a_build_config_file

However right now the generated code just reorders all of the fields into alphabetical order.

For many of the underlying protos, the field order is an intentional choice.  Going back to the cloudbuild example, having the image `name` first immediately followed by `args` helps readability, since name of the image really frames the context for the rest of the fields:

```
- name: gcr.io/cloud-builders/some-builder
  args: ['build', 'some', 'thing']
  env: ...
  ...
```

vs

```
- args: ['build', 'some', 'thing']
  dir: ...
  env: ...
  id: ...
  name: way-down-here
  volumes: (buried by yet more arguments)
  waitfor:
```

This becomes more of issue if we're using the generated code to automatically create a `yaml` file which might then need to be read (or even modified by hand) at a later point in time.
